Module 3 - Automation testing
JoanneEvenett/DevOps-Course-Starter- pull request #4
Opened 2021-04-23 10:27 UTC by JoanneEvenett

Please make sure you are raising this PR against your own repository and not the original. If it says https://github.com/CorndelWithSoftwire in the search bar right now, you are in the wrong place!

Please also don't forget to submit the PR's url to Aptem afterwards (by clicking on the corresponding exercise component, pasting the url in the textbox that appears and then pressing the finish button).

2021-04-23 10:28 UTC, JoanneEvenett commented
Apologies this is sooooo incomplete

2021-05-14 16:36 UTC, JackMead requested changes
This is a good start, I was able to access your app, and see the newer/older todos (although it wasn't obvious from the index page that I might need to guess some URLs!), and you've got a working unit test (though you correctly noted that some of those unit tests are crossing into integration tests). However, I wasn't able to run the integration tests with patching, or your end-to-end tests. I've left some thoughts below on those, but note that it'll be very helpful at this stage to convert back to using the `.env` file for secrets rather than your custom solution so that your tests can effectively override those values. Feel free to reach out if any of the feedback here isn't clear or you need any extra guidance

2021-05-14 16:36 UTC, JackMead commented on tests/EndtoEnd/test_todo_end_to_end.py
> +    os.environ[board_id]
Because of your custom secrets.txt file, this isn't going to do anything! The easiest solution here is likely to be switching to using the `.env` file - reading the board/list ids out of the environment variables in your application code, and you can then override those from your tests like this

2021-05-14 16:36 UTC, JackMead commented on tests/test_todo_integration_tests.py
> +@patch('requests.get')
Here you're patching `requests.get` but your code is using `requests.request` so this is never being hit

2021-05-14 16:36 UTC, JackMead commented on tests/test_todo_integration_tests.py
> +def test_loading_page(client):
This test is only passing because it's genuinely talking to Trello - we haven't patched out any requests, so it's acting as an end-to-end test. We should change this to mock those requests

2021-05-14 16:36 UTC, JackMead commented on tests/test_todo_integration_tests.py
> +    mock_get_requests.side_effect = mock_get_lists("https://api.trello.com/1/boards/6050cee9111302705ff69916/lists")#ideally would read Id from the secrets file
Slight mismatch in usage here, we want to set the side_effect to a function, for which the arguments will be passed by whatever uses our patched function; so e.g. here:
`mock_get_requests.side_effect = mock_get_lists`

2021-05-14 16:36 UTC, JackMead commented on todo_app/app.py
> +        todoList = get_cards_on_lists("6050cee9111302705ff69917")
It's reasonable to set these in config rather than loading them by name from Trello but our app isn't going to be testable if these list ids are hard coded here - we should move those into the .env file as well and load them in here

2021-05-14 16:36 UTC, JackMead commented on todo_app/model/trellomodel.py
> +        if sum(1 for i in self._all_done_items) > 5:
Since _all_done_items is a list, we could here just use the length: `if len(self._all_done_items) > 5:`

2021-05-14 16:36 UTC, JackMead commented on todo_app/trelloApiCalls.py
> +    log.info(token)#
We definitely don't want to be logging out our key and token!

2021-05-14 16:36 UTC, JackMead commented on tests/test_todo_unittest.py
> +def test_todoLists():#unit or integration test?
You're right that this unclear - the test itself is verifying that the lists passed through to the class are matched up correctly, so in that sense this is a unit test, but in the setup you've genuinely connected to Trello which is unusual. To keep the scope of this more defined, we should instead define those lists statically like you did in the first unit test.

2021-05-14 16:36 UTC, JackMead commented on README.md
> +tests > test_todo_unittest.py
We should make sure that these are also runnable via the terminal, e.g. with `poetry run pytest` - VSCode's test explorer can take extra steps that we won't be able to rely on in all environments

2021-06-08 14:48 UTC, merged